export enum CaseState {
  DRAFT = 'DRAFT',
  CONSENT_PENDING = 'CONSENT_PENDING',
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  SOURCE_LINKING = 'SOURCE_LINKING',
  DATA_FETCHING = 'DATA_FETCHING',
  DATA_READY = 'DATA_READY',
  SCORING = 'SCORING',
  SCORED = 'SCORED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DECISIONED = 'DECISIONED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  EXPIRED = 'EXPIRED',
  FAILED = 'FAILED',
}

export enum ConsentStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  AMENDED = 'AMENDED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

export enum SourceType {
  AA = 'AA',
  GST = 'GST',
  BUREAU = 'BUREAU',
  UPI = 'UPI',
  EPFO = 'EPFO',
  REGISTRATION = 'REGISTRATION',
  INVOICE = 'INVOICE',
  POS = 'POS',
  ECOMMERCE = 'ECOMMERCE',
  ONDC = 'ONDC',
  UTILITY = 'UTILITY',
}

export enum SourceLinkStatus {
  PENDING = 'PENDING',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum FetchStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL',
  RETRYING = 'RETRYING',
}

export enum PillarName {
  REVENUE_STABILITY = 'REVENUE_STABILITY',
  CASH_FLOW_HEALTH = 'CASH_FLOW_HEALTH',
  COMPLIANCE_DISCIPLINE = 'COMPLIANCE_DISCIPLINE',
  OPERATIONAL_MATURITY = 'OPERATIONAL_MATURITY',
  CREDIT_BEHAVIOR = 'CREDIT_BEHAVIOR',
  DIGITAL_COMMERCIAL_ACTIVITY = 'DIGITAL_COMMERCIAL_ACTIVITY',
}

export enum DecisionType {
  APPROVE = 'APPROVE',
  DECLINE = 'DECLINE',
  REFER = 'REFER',
  REQUEST_MORE_DATA = 'REQUEST_MORE_DATA',
}

export enum HealthBand {
  STRONG = 'STRONG',
  PROMISING_BUT_THIN = 'PROMISING_BUT_THIN',
  RISKY = 'RISKY',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  UNDERWRITER = 'UNDERWRITER',
  RELATIONSHIP_MANAGER = 'RELATIONSHIP_MANAGER',
  RISK_REVIEWER = 'RISK_REVIEWER',
  COMPLIANCE_REVIEWER = 'COMPLIANCE_REVIEWER',
  OPERATIONS = 'OPERATIONS',
  VIEWER = 'VIEWER',
}

export enum AlertSeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO',
}

export enum AlertStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum AuditActionType {
  CASE_CREATED = 'CASE_CREATED',
  CASE_STATE_CHANGED = 'CASE_STATE_CHANGED',
  CONSENT_GRANTED = 'CONSENT_GRANTED',
  CONSENT_REVOKED = 'CONSENT_REVOKED',
  CONSENT_AMENDED = 'CONSENT_AMENDED',
  SOURCE_LINKED = 'SOURCE_LINKED',
  SOURCE_UNLINKED = 'SOURCE_UNLINKED',
  DATA_FETCHED = 'DATA_FETCHED',
  DATA_FETCH_FAILED = 'DATA_FETCH_FAILED',
  SCORING_COMPLETED = 'SCORING_COMPLETED',
  DECISION_MADE = 'DECISION_MADE',
  DECISION_OVERRIDDEN = 'DECISION_OVERRIDDEN',
  NOTE_ADDED = 'NOTE_ADDED',
  NOTE_EDITED = 'NOTE_EDITED',
  NOTE_DELETED = 'NOTE_DELETED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  POLICY_CREATED = 'POLICY_CREATED',
  POLICY_UPDATED = 'POLICY_UPDATED',
  MODEL_PROMOTED = 'MODEL_PROMOTED',
  MODEL_ROLLED_BACK = 'MODEL_ROLLED_BACK',
  SETTINGS_CHANGED = 'SETTINGS_CHANGED',
  FEATURE_FLAG_TOGGLED = 'FEATURE_FLAG_TOGGLED',
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  RETENTION_PURGE = 'RETENTION_PURGE',
}

export enum EntityType {
  BUSINESS = 'BUSINESS',
  SOLE_PROPRIETORSHIP = 'SOLE_PROPRIETORSHIP',
  PARTNERSHIP = 'PARTNERSHIP',
  LLP = 'LLP',
  PRIVATE_LIMITED = 'PRIVATE_LIMITED',
  PUBLIC_LIMITED = 'PUBLIC_LIMITED',
  TRUST = 'TRUST',
  SOCIETY = 'SOCIETY',
}

export enum SectorType {
  RETAIL = 'RETAIL',
  MANUFACTURING = 'MANUFACTURING',
  WHOLESALE = 'WHOLESALE',
  LOGISTICS = 'LOGISTICS',
  SERVICES = 'SERVICES',
  RESTAURANT = 'RESTAURANT',
  TRADER = 'TRADER',
  ECOMMERCE = 'ECOMMERCE',
  AGRICULTURE = 'AGRICULTURE',
  CONSTRUCTION = 'CONSTRUCTION',
  HEALTHCARE = 'HEALTHCARE',
  IT = 'IT',
  OTHER = 'OTHER',
}
